### ISSUE TITLE
Create self-contained html file

### ISSUE THREAD

**Issue by rleyvasal** [evilz/vscode-reveal#1017]
Is there a way to create a self-contained htm file  in vscode-reveal (one html without extra folders)? like the way this is done with revealjs markdown presentations in the following:

https://quarto.org/docs/presentations/revealjs/presenting.html

Code to create self-contained html file: 

```yaml
---
title: "Presentation"
format:
  revealjs:
    self-contained: true
---
```
