### ISSUE TITLE
CustomTheme is overridden by default theme on template.marko

### ISSUE THREAD

**Issue by leiming** [evilz/vscode-reveal#142]
At https://github.com/evilz/vscode-reveal/commit/30eaecc56113e3a05768ecee851cf28b786ad763

I've found that `views/template.marko` insert style code below that break my customTheme:

```css
.hljs {
  background: none;
}
.reveal pre {
  width: 98%;
  margin: 0px;
  box-shadow: none;
}
.reveal pre code {
  font-size: 1.2em;
  line-height: 1.2;
  border-radius: 10px;
  max-height: 60vh !important;
  overflow: hidden !important;
}
```

My customTheme code **CANNOT** override the default style :
```css
  pre {
    code {
      font-size: 1rem;
    }
  }
```

Could you help me how to fix it or recovery the origin style? 
Thanks.
