### ISSUE TITLE
feature request: add htmlFragment option

### ISSUE THREAD

**Issue by unional** [evilz/vscode-reveal#772]
I want to add a background video to the whole deck.

I can do it with html, but not with markdown.
It would be great if we can add an option to point to a html fragment in the yaml section, and inject that fragment into the resulting html.

e.g.:

slides.md

```md
---
htmlFragment: fragment.html
customStyle: my-style.css
---

the slides...
```

fragment.html

```html
<video id="background-video" src="..."/>
```

my-style.css

```css
  #background-video {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%;
    min-height: 100%;
  }
  ```
