### ISSUE TITLE
`data-background-transition` not working

### ISSUE THREAD

**Issue by rleyvasal** [evilz/vscode-reveal#922]
[revealjs  example](https://revealjs.com/#/16) shows how the background transition should work; however, setting the following code in `vscode-reveal` does not produce the desired effect. 

```yaml
---
theme : "white"
transition: "slide"
slideNumber: false
---

## first slide

---

## second slide

<!-- .slide: data-background="#43464B" data-background-transition="zoom" -->

## Background Transitions

Different background transitions are available via the backgroundTransition option. This one's called "zoom".


```
